apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-f7or
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-f7or
    app.kubernetes.io/part-of: my-app-1
  name: devfile-sample-f7or
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-f7or
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-f7or
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/relimele-tenant/my-app-1/devfile-sample-f7or@sha256:5e3ff4bb04bd1c3297ce896b6ef030d3dd1035ccfd7a2348d5aac4c36a0aea15
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
